# Generated by Django 5.2.7 on 2025-11-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_fading_text_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='external_url',
            field=models.URLField(blank=True, help_text='Оставьте пустым, если тренажер открывается на этом сайте', null=True, verbose_name='Ссылка на тренажер'),
        ),
    ]
