# Generated by Django 5.2.7 on 2025-11-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('accent_color', models.CharField(blank=True, help_text='HEX-цвет для оформления карточек', max_length=9, verbose_name='Цвет акцента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Набор флеш-карт',
                'verbose_name_plural': 'Наборы флеш-карт',
                'db_table': 'flash_cards_deck',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField(verbose_name='Текст лицевой стороны')),
                ('back_text', models.TextField(verbose_name='Ответ / оборот')),
                ('hint', models.CharField(blank=True, help_text='Короткий намёк, который поможет вспомнить ответ', max_length=255, verbose_name='Подсказка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trainers_flash_cards.flashcarddeck', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Флеш-карта',
                'verbose_name_plural': 'Флеш-карты',
                'db_table': 'flash_cards_card',
                'ordering': ['deck', 'order', 'id'],
            },
        ),
    ]
