# Generated by Django 5.2.7 on 2025-11-12 19:06

from django.db import migrations

WORDS = [
    "ас",
    "ам",
    "ум",
    "ус",
    "ос",
    "ом",
    "ма",
    "со",
    "су",
    "му",
    "са",
]


LEVEL_DATA = {
    "slug": "flash-words-level-1",
    "title": "а, у, о, м, с (1) — 11 слов(а)",
    "description": "Комбинации букв а, у, о, м, с для тренировки памяти.",
    "accent_color": "#FF9F68",
}


def seed_level(apps, schema_editor):
    deck_model = apps.get_model("trainers_flash_cards", "FlashCardDeck")
    card_model = apps.get_model("trainers_flash_cards", "FlashCard")

    deck, _ = deck_model.objects.get_or_create(
        slug=LEVEL_DATA["slug"],
        defaults={
            "title": LEVEL_DATA["title"],
            "description": LEVEL_DATA["description"],
            "accent_color": LEVEL_DATA["accent_color"],
        },
    )

    existing_words = set(
        card_model.objects.filter(deck=deck).values_list("front_text", flat=True)
    )

    for order, word in enumerate(WORDS, start=1):
        if word in existing_words:
            continue
        card_model.objects.create(
            deck=deck,
            front_text=word,
            back_text=word,
            hint="",
            order=order,
        )


def remove_level(apps, schema_editor):
    deck_model = apps.get_model("trainers_flash_cards", "FlashCardDeck")
    deck_model.objects.filter(slug=LEVEL_DATA["slug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trainers_flash_cards", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_level, remove_level),
    ]
