# Generated by Django 4.2.7 on 2025-11-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_seed_speed_reading_trainers'),
        ('trainers_flash_cards', '0002_seed_initial_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcarddeck',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Набор флеш-карт', 'verbose_name_plural': 'Наборы флеш-карт'},
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to='trainers.trainer', verbose_name='Тренажер'),
        ),
    ]
