# Generated by Django 4.2.7 on 2025-11-13 05:09

from django.db import migrations, models
import django.db.models.deletion


def link_flash_words_decks(apps, schema_editor):
    Trainer = apps.get_model('trainers', 'Trainer')
    FlashCardDeck = apps.get_model('trainers_flash_cards', 'FlashCardDeck')

    trainer = Trainer.objects.filter(slug='flash-words').first()
    if trainer is None:
        return

    decks = FlashCardDeck.objects.filter(trainer__isnull=True).order_by('created_at', 'id')
    for order, deck in enumerate(decks, start=1):
        deck.trainer = trainer
        deck.order = deck.order or order
        deck.save(update_fields=['trainer', 'order'])


def unlink_flash_words_decks(apps, schema_editor):
    FlashCardDeck = apps.get_model('trainers_flash_cards', 'FlashCardDeck')
    FlashCardDeck.objects.filter(trainer__slug='flash-words').update(trainer=None)


class Migration(migrations.Migration):

    dependencies = [
        ('trainers_flash_cards', '0003_alter_flashcarddeck_options_flashcarddeck_is_active_and_more'),
    ]

    operations = [
        migrations.RunPython(link_flash_words_decks, unlink_flash_words_decks),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='trainer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='flashcard_decks',
                to='trainers.trainer',
                verbose_name='Тренажер',
            ),
        ),
    ]
