# Generated by Django 5.2.7 on 2025-11-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='TrainerDifficulty',
                ),
            ],
            database_operations=[],
        ),
    ]
