# Generated by Django 4.2.7 on 2025-11-13 05:09

from django.db import migrations


TRAINERS = [
    {
        "slug": "fading-text",
        "title": "Тренажер «Исчезающий текст»",
        "lead": (
            "Ребёнок должен успеть прочитать фразу до того, как она исчезнет. "
            "Укрепляет внимательность и ускоряет восприятие текста."
        ),
        "image": "/images/trainers/speed-reading/fading-text.svg",
        "external_url": "",
        "program": "Скорочтение",
        "accent_color": "#5C78D6",
        "position": 1,
        "is_active": True,
    },
    {
        "slug": "schulte-table",
        "title": "Тренажер «Таблица Шульте»",
        "lead": (
            "Классическая таблица Шульте развивает концентрацию: нужно быстро находить числа "
            "по возрастанию, удерживая взгляд на всей поверхности поля."
        ),
        "image": "/images/trainers/speed-reading/schulte-table.svg",
        "external_url": "",
        "program": "Скорочтение",
        "accent_color": "#27AE60",
        "position": 2,
        "is_active": True,
    },
    {
        "slug": "flash-words",
        "title": "Тренажер «Флеш-слова»",
        "lead": (
            "На экране всплывают слова с заданной скоростью. Их нужно запомнить и воспроизвести "
            "в той же последовательности, чтобы тренировать память и внимание."
        ),
        "image": "/images/trainers/speed-reading/flash-words.svg",
        "external_url": "",
        "program": "Скорочтение",
        "accent_color": "#FF9F68",
        "position": 3,
        "is_active": True,
    },
    {
        "slug": "stroop-test",
        "title": "Тренажер «Тест Струпа»",
        "lead": (
            "Карточки с названиями цветов, написанными разными оттенками. Нужно быстро выбрать "
            "правильный ответ, чтобы развивать переключаемость внимания."
        ),
        "image": "/images/trainers/speed-reading/stroop-test.svg",
        "external_url": "",
        "program": "Скорочтение",
        "accent_color": "#9B59B6",
        "position": 4,
        "is_active": True,
    },
]

NEW_SLUGS = {item["slug"] for item in TRAINERS if item["slug"] != "fading-text"}


def seed_trainers(apps, schema_editor):
    Trainer = apps.get_model("trainers", "Trainer")

    for item in TRAINERS:
        defaults = item.copy()
        slug = defaults.pop("slug")
        Trainer.objects.update_or_create(slug=slug, defaults=defaults)


def unseed_trainers(apps, schema_editor):
    Trainer = apps.get_model("trainers", "Trainer")
    if NEW_SLUGS:
        Trainer.objects.filter(slug__in=NEW_SLUGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_delete_trainerdifficulty"),
    ]

    operations = [
        migrations.RunPython(seed_trainers, unseed_trainers),
    ]
