# Generated by Django 4.2.7 on 2025-11-13 05:09

from django.db import migrations


LEVELS = [
    {
        "title": "3×3 — старт",
        "grid_size": 3,
        "numbers_layout": [1, 5, 9, 2, 6, 3, 7, 4, 8],
        "time_limit_seconds": 45,
        "order": 1,
    },
    {
        "title": "4×4 — классика",
        "grid_size": 4,
        "numbers_layout": [
            1,
            15,
            6,
            10,
            12,
            5,
            7,
            2,
            14,
            3,
            11,
            8,
            4,
            13,
            9,
            16,
        ],
        "time_limit_seconds": 60,
        "order": 2,
    },
    {
        "title": "5×5 — продвинутый",
        "grid_size": 5,
        "numbers_layout": [
            7,
            3,
            22,
            9,
            18,
            11,
            1,
            16,
            5,
            23,
            20,
            14,
            2,
            24,
            8,
            12,
            19,
            4,
            21,
            6,
            15,
            10,
            25,
            17,
            13,
        ],
        "time_limit_seconds": 90,
        "order": 3,
    },
]


def seed_levels(apps, schema_editor):
    Trainer = apps.get_model('trainers', 'Trainer')
    SchulteTableLevel = apps.get_model('trainers_schulte_table', 'SchulteTableLevel')

    trainer = Trainer.objects.filter(slug='schulte-table').first()
    if trainer is None:
        return

    for item in LEVELS:
        defaults = item.copy()
        SchulteTableLevel.objects.update_or_create(
            trainer=trainer,
            grid_size=item['grid_size'],
            defaults=defaults,
        )


def remove_levels(apps, schema_editor):
    SchulteTableLevel = apps.get_model('trainers_schulte_table', 'SchulteTableLevel')
    SchulteTableLevel.objects.filter(trainer__slug='schulte-table').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_seed_speed_reading_trainers'),
        ('trainers_schulte_table', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_levels, remove_levels),
    ]
